services:
  - type: web
    name: smax-aviator-presentation
    env: static
    buildCommand: echo "No build required for static site"
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /
        destination: /smax-aviator-presentation.html
